// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Structure;

public partial class AnalyticsRevenueLog
{
    public long Id { get; set; }

    public long PlanId { get; set; }

    public long SubscriptionId { get; set; }

    public DateTime TransactionDate { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; }

    public string TransactionId { get; set; }

    public string Status { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual SubscriptionPlan Plan { get; set; }

    public virtual UserSubscription Subscription { get; set; }
}