// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Structure;

public partial class ChatRoomFolder
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long UserId { get; set; }

    public long? ParentFolderId { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<ChatRoomFolder> InverseParentFolder { get; set; } = new List<ChatRoomFolder>();

    public virtual ChatRoomFolder ParentFolder { get; set; }

    public virtual User User { get; set; }
}