// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Structure;

public partial class ChatRoom
{
    public long Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime? LastActivityAt { get; set; }

    public bool IsFavorite { get; set; }

    public string Status { get; set; }

    public string Tags { get; set; }

    public string FolderPath { get; set; }

    public long UserId { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<ChatMessage> ChatMessages { get; set; } = new List<ChatMessage>();

    public virtual ICollection<ConversationTracking> ConversationTrackings { get; set; } = new List<ConversationTracking>();

    public virtual User User { get; set; }
}