// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Structure;

public partial class ChatMessage
{
    public long Id { get; set; }

    public long ChatRoomId { get; set; }

    public string SenderId { get; set; }

    /// <summary>
    /// user or system
    /// </summary>
    public string Role { get; set; }

    public string Content { get; set; }

    public DateTime Timestamp { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ChatRoom ChatRoom { get; set; }
}