// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Structure;

public partial class ConversationTracking
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public long RoomId { get; set; }

    public string ConversationId { get; set; }

    public string UserQuery { get; set; }

    public string AiResponse { get; set; }

    public string Topic { get; set; }

    public string Language { get; set; }

    public string MetadataJson { get; set; }

    public DateTime Timestamp { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<ConversationKeyword> ConversationKeywords { get; set; } = new List<ConversationKeyword>();

    public virtual ICollection<ConversationPdfReference> ConversationPdfReferences { get; set; } = new List<ConversationPdfReference>();

    public virtual ChatRoom Room { get; set; }

    public virtual User User { get; set; }
}