// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Structure;

public partial class ConversationPdfReference
{
    public long Id { get; set; }

    public long ConversationId { get; set; }

    public string FileName { get; set; }

    public long FileId { get; set; }

    public long RelevanceScore { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ConversationTracking Conversation { get; set; }

    public virtual DataSourceFile File { get; set; }
}