// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Structure;

public partial class DiscountCoupon
{
    public long Id { get; set; }

    public string Code { get; set; }

    public double DiscountValue { get; set; }

    /// <summary>
    /// Percentage, Fixed
    /// </summary>
    public double DiscountType { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public long? MaxUses { get; set; }

    public long CurrentUses { get; set; }

    public bool IsActive { get; set; }

    public string Description { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<CouponPlan> CouponPlans { get; set; } = new List<CouponPlan>();
}