// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Structure;

public partial class Invoice
{
    public long Id { get; set; }

    public long PlanId { get; set; }

    public long UserId { get; set; }

    /// <summary>
    /// NewSubscription, Renewal, Upgrade, Downgrade, Refund
    /// </summary>
    public string Type { get; set; }

    public double Amount { get; set; }

    public double DiscountAmount { get; set; }

    public double TotalAmount { get; set; }

    public string CouponCode { get; set; }

    public string InvoiceNumber { get; set; }

    /// <summary>
    /// Pending, Completed, Failed, Cancelled, Refunded
    /// </summary>
    public string Status { get; set; }

    public string PaymentGatewayTransactionId { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime TransactionDate { get; set; }

    public string Notes { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual User User { get; set; }
}