// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Structure;

/// <summary>
/// جدول لفئات الاستعلامات القانونية
/// </summary>
public partial class LegalCategory
{
    public long Id { get; set; }

    public string Name { get; set; }

    public bool IsActive { get; set; }

    public string Description { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<MessageCategory> MessageCategories { get; set; } = new List<MessageCategory>();
}