// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Structure;

public partial class MessageCategory
{
    public long Id { get; set; }

    public long LegalCategoryId { get; set; }

    public long MessageId { get; set; }

    public decimal Confidence { get; set; }

    public bool IsAutoClassified { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual LegalCategory LegalCategory { get; set; }

    public virtual ChatMessage Message { get; set; }
}