// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Structure;

public partial class PlanFeature
{
    public long Id { get; set; }

    public long PlanId { get; set; }

    public string Feature { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual SubscriptionPlan Plan { get; set; }
}