// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Structure;

public partial class RefreshToken
{
    public long Id { get; set; }

    public string Token { get; set; }

    public DateTime ExpiresAt { get; set; }

    public DateTime? RevokedAt { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public bool IsDeleted { get; set; }

    public long UserId { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual User User { get; set; }
}