// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Structure;

public partial class SubscriptionPlan
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public double PriceMonthly { get; set; }

    public double PriceYearly { get; set; }

    public bool IsActive { get; set; }

    public long? AllowedChatRooms { get; set; }

    public long? AllowedFiles { get; set; }

    public long? AllowedFileSizeMb { get; set; }

    public bool IsTrial { get; set; }

    public long? TrialDays { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<CouponPlan> CouponPlans { get; set; } = new List<CouponPlan>();

    public virtual ICollection<PlanFeature> PlanFeatures { get; set; } = new List<PlanFeature>();

    public virtual ICollection<UserSubscription> UserSubscriptions { get; set; } = new List<UserSubscription>();
}