// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Structure;

public partial class UserSubscription
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public long PlanId { get; set; }

    /// <summary>
    /// Active, Trial, Expired, Cancelled, Suspended
    /// </summary>
    public string Status { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    /// <summary>
    /// Monthly, Yearly, For Ever
    /// </summary>
    public string PeriodType { get; set; }

    public bool? AutoRenew { get; set; }

    public long? LastInvoiceId { get; set; }

    public DateTime? LastRenewalDate { get; set; }

    public long QueriesUsedToday { get; set; }

    public long QueriesUsedThisMonth { get; set; }

    public DateTime? LastQueryDate { get; set; }

    public string PaymentGatewayTransactionId { get; set; }

    public string PaymentMethod { get; set; }

    public string Notes { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<AnalyticsRevenueLog> AnalyticsRevenueLogs { get; set; } = new List<AnalyticsRevenueLog>();

    public virtual SubscriptionPlan Plan { get; set; }

    public virtual User User { get; set; }
}