// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Structure;

public partial class UserActivityLog
{
    public long Id { get; set; }

    public long UserId { get; set; }

    /// <summary>
    /// Login, Logout, CreateChatRoom, SendMessage, etc.
    /// </summary>
    public string ActivityType { get; set; }

    public string Description { get; set; }

    public string IpAddress { get; set; }

    public string UserAgent { get; set; }

    public DateTime Timestamp { get; set; }

    public virtual User User { get; set; }
}