// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Structure;

public partial class User
{
    public long Id { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string FirstName { get; set; }

    public int? MiddleName { get; set; }

    public string? LastName { get; set; }

    public string GoogleId { get; set; }

    public bool IsEmailConfirmed { get; set; }

    public string PasswordHash { get; set; }

    public long? PhoneNumber { get; set; }

    public bool PhoneNumberConfirmed { get; set; }

    public string LogInType { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public bool IsActive { get; set; }

    /// <summary>
    /// User, Admin
    /// </summary>
    public string UserRole { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<ConversationTracking> ConversationTrackings { get; set; } = new List<ConversationTracking>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    public virtual ICollection<UserActivityLog> UserActivityLogs { get; set; } = new List<UserActivityLog>();

    public virtual ICollection<UserSubscription> UserSubscriptions { get; set; } = new List<UserSubscription>();
}